version: '3.4'

x-app-service-template: &app
  build: rails_app
  image: yabeda-rails-app:1.0
  volumes:
    - ./rails_app:/app

services:
  nginx:
    image: ichai/nginx-lua-prometheus:latest
    ports:
      - 8000:80  
    depends_on:
      - redis
      - sidekiq     
    volumes:
      - ./nginx/rails.conf:/etc/nginx/conf.d/rails.conf     

  rails:
    <<: *app
    ports:
      - 5000:5000
    environment:
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true
    depends_on:
      - redis

    command: bundle exec puma -C config/puma.rb

  sidekiq:
    <<: *app
    ports:
      - 5100:5100
    environment:
      PORT: 5100
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

    command: sidekiq -C config/sidekiq.yml

  redis:
    image: redis
    command: redis-server

  grafana:
    image: grafana/grafana:5.2.4
    depends_on:
      - prometheus    
    ports:
      - 3000:3000/tcp
    volumes: 
      - ./grafana_db:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.4.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    depends_on:
      - rails

    command:
      - --config.file=/etc/prometheus/prometheus.yml

  rails_stressor:
    build: rails_stressor
    image: rails_stressor
    depends_on:
      - rails
    command: -z 2m -c 15 -m GET http://nginx:80
